#Pipeline for a .Net Docker image using GitHub actions on the dev branch

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    env:
      IMAGE_NAME: refactoringchallengeapi
      BUILD_CONFIGURATION: --debug
      DOCKER_REGISTRY: DockerRegistry

#Restore, build and test the solution before creating the docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build and Test
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} && dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Deployment/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            BUILD_CONFIGURATION=${{ env.BUILD_CONFIGURATION }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
        env:
          DOCKER_USERNAME: TestUserName
          DOCKER_PASSWORD: TestPassword 
      
      
      

