#Pipeline for a .Net Docker image using GitHub actions on the dev branch

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
    imageName: refactoringchallengeapi
    buildConfiguration: Debug
    dockerRegistry: docker.io

#Restore, build and test the solution before creating the docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build and Test
        run: dotnet build --configuration ${{ env.buildConfiguration }} && dotnet test --configuration ${{ env.buildConfiguration }} || true
        continue-on-error: true
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./Technical-Challenge/RefactoringChallenge.Api/../Dockerfile
          file: Dockerfile
          push: true
          tags: ${{ env.imageName }}
          build-args: |
            BUILD_CONFIGURATION=${{ env.buildConfiguration }}
          cache-from: type=registry,ref=${{ env.dockerRegistry }}/${{ env.imageName }}:latest
          cache-to: type=inline
        env:
          DOCKER_USERNAME: TestUserName
          DOCKER_PASSWORD: TestPassword 
      
      
      

